import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1785688241033 implements MigrationInterface {
    name = 'InitialSchema1785688241033'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."ad_campaigns_status_enum" AS ENUM('draft', 'active', 'paused', 'completed')`);
        await queryRunner.query(`CREATE TABLE "ad_campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "advertiserName" character varying NOT NULL, "budget" numeric(12,2), "status" "public"."ad_campaigns_status_enum" NOT NULL DEFAULT 'draft', "startDate" TIMESTAMP, "endDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7877713eb87f782dd190eed85a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."banner_ads_placement_enum" AS ENUM('home_screen', 'ride_screen', 'search_results', 'receipt')`);
        await queryRunner.query(`CREATE TABLE "banner_ads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "campaignId" character varying, "title" character varying NOT NULL, "imageUrl" character varying NOT NULL, "targetUrl" character varying NOT NULL, "placement" "public"."banner_ads_placement_enum" NOT NULL, "impressions" integer NOT NULL DEFAULT '0', "clicks" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "startDate" TIMESTAMP, "endDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_77d1190388f14e6d3d1bf140ad8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fcffbe533565f62ddcbd966221" ON "banner_ads"  ("placement") `);
        await queryRunner.query(`CREATE TABLE "sponsored_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "campaignId" character varying, "name" character varying NOT NULL, "lat" double precision NOT NULL, "lng" double precision NOT NULL, "radiusKm" double precision NOT NULL DEFAULT '2', "iconUrl" character varying, "targetUrl" character varying, "impressions" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5aabb69d0666521611a11d3feb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."airport_queue_entries_status_enum" AS ENUM('waiting', 'dispatched', 'left')`);
        await queryRunner.query(`CREATE TABLE "airport_queue_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "airportId" character varying NOT NULL, "driverUserId" character varying NOT NULL, "status" "public"."airport_queue_entries_status_enum" NOT NULL DEFAULT 'waiting', "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), "dispatchedAt" TIMESTAMP, CONSTRAINT "PK_7089a97e937c0b825540a976df2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b28c236bb7cfa154d8edc5f1f" ON "airport_queue_entries"  ("airportId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d2215326ea228a5b859b627a0" ON "airport_queue_entries"  ("driverUserId") `);
        await queryRunner.query(`CREATE TABLE "airports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "iataCode" character varying NOT NULL, "city" character varying NOT NULL, "lat" double precision NOT NULL, "lng" double precision NOT NULL, "geofenceRadiusKm" double precision NOT NULL DEFAULT '2', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_66b7b2c37c035081115fdde45ba" UNIQUE ("iataCode"), CONSTRAINT "PK_507127316cedb7ec7447d0cb3d7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_66b7b2c37c035081115fdde45b" ON "airports"  ("iataCode") `);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "hashedKey" character varying NOT NULL, "keyPrefix" character varying NOT NULL, "scopes" jsonb NOT NULL DEFAULT '[]', "isActive" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0d632a6c3b16bc708bf0987fed2" UNIQUE ("hashedKey"), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0d632a6c3b16bc708bf0987fed" ON "api_keys"  ("hashedKey") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorUserId" character varying, "actorRole" character varying, "action" character varying NOT NULL, "targetType" character varying, "targetId" character varying, "metadata" jsonb, "ipAddress" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e36d23e1e7cf81ea77758bef79" ON "audit_logs"  ("actorUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs"  ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_fcfb9137823075fb3162b82f73" ON "audit_logs"  ("targetId") `);
        await queryRunner.query(`CREATE TABLE "otp_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "destination" character varying NOT NULL, "code" character varying NOT NULL, "isUsed" boolean NOT NULL DEFAULT false, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9d0487965ac1837d57fec4d6a26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9d38771dd102800f389f4c73ae" ON "otp_codes"  ("destination") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "tokenHash" character varying NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c25bc63d248ca90e8dcc1d92d06" UNIQUE ("tokenHash"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens"  ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens"  ("tokenHash") `);
        await queryRunner.query(`CREATE TABLE "announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "body" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "startDate" TIMESTAMP, "endDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cms_pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "slug" character varying NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "isPublished" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_164bf011d905e86e677bc86a1e9" UNIQUE ("slug"), CONSTRAINT "PK_a6bd4d97252f8f122d34bc6bce6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_164bf011d905e86e677bc86a1e" ON "cms_pages"  ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."commission_rules_driverlevel_enum" AS ENUM('rookie', 'standard', 'silver', 'gold', 'platinum', 'diamond', 'elite')`);
        await queryRunner.query(`CREATE TYPE "public"."commission_rules_vehiclecategory_enum" AS ENUM('car', 'suv', 'taxi', 'luxury', 'ev', 'motorcycle', 'tricycle', 'van', 'bus', 'truck')`);
        await queryRunner.query(`CREATE TABLE "commission_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverLevel" "public"."commission_rules_driverlevel_enum", "city" character varying, "vehicleCategory" "public"."commission_rules_vehiclecategory_enum", "commissionPercent" numeric(5,2) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_399c9fa57f7fd28dfc57acea3bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "corporate_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownerUserId" character varying NOT NULL, "companyName" character varying NOT NULL, "budgetBalance" numeric(14,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'NGN', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f7fdb2488106dd5c78600c06df3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_541734cca61b7cb40ab27085e3" ON "corporate_accounts"  ("ownerUserId") `);
        await queryRunner.query(`CREATE TABLE "corporate_employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "corporateAccountId" character varying NOT NULL, "userId" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ab843c3599b19d51dc6d7cca47c" UNIQUE ("userId"), CONSTRAINT "PK_70cddfff430d10f7bfc9626bac2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_55c425dde4e4d3b2c5fd4a1ecc" ON "corporate_employees"  ("corporateAccountId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ab843c3599b19d51dc6d7cca47" ON "corporate_employees"  ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."corporate_transactions_direction_enum" AS ENUM('credit', 'debit')`);
        await queryRunner.query(`CREATE TABLE "corporate_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "corporateAccountId" character varying NOT NULL, "direction" "public"."corporate_transactions_direction_enum" NOT NULL, "amount" numeric(14,2) NOT NULL, "balanceAfter" numeric(14,2) NOT NULL, "referenceId" character varying, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8ec1f38a02bd83073c7101b7f5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_be01460a12c312aa6bca798de6" ON "corporate_transactions"  ("corporateAccountId") `);
        await queryRunner.query(`CREATE TYPE "public"."ride_offers_status_enum" AS ENUM('pending', 'accepted', 'declined', 'expired', 'superseded')`);
        await queryRunner.query(`CREATE TABLE "ride_offers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rideId" character varying NOT NULL, "driverUserId" character varying NOT NULL, "status" "public"."ride_offers_status_enum" NOT NULL DEFAULT 'pending', "distanceKm" double precision NOT NULL, "offeredAt" TIMESTAMP NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP NOT NULL, CONSTRAINT "PK_8bd0ac2b8b108f575ceea9cb433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e47debd3d44368f977ae7b6b81" ON "ride_offers"  ("rideId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2883d65c5168c5708990302325" ON "ride_offers"  ("driverUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."driver_documents_type_enum" AS ENUM('drivers_license', 'insurance', 'road_worthiness', 'profile_photo', 'vehicle_photo', 'background_check')`);
        await queryRunner.query(`CREATE TYPE "public"."driver_documents_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "driver_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverProfileId" character varying NOT NULL, "type" "public"."driver_documents_type_enum" NOT NULL, "documentUrl" character varying NOT NULL, "status" "public"."driver_documents_status_enum" NOT NULL DEFAULT 'pending', "reviewedBy" character varying, "rejectionReason" character varying, "expiryDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_31c28b4e8f55a5d411597d45ab2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d2841db94a1991f825d16e9dfb" ON "driver_documents"  ("driverProfileId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('passenger', 'driver', 'admin', 'super_admin', 'dispatcher', 'fleet_owner', 'corporate', 'country_admin', 'city_manager', 'support_agent', 'finance', 'marketing', 'auditor')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "phone" character varying NOT NULL, "email" character varying, "passwordHash" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'passenger', "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "profilePhotoUrl" character varying, "isPhoneVerified" boolean NOT NULL DEFAULT false, "isEmailVerified" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "rating" numeric(3,2) NOT NULL DEFAULT '5', "ratingCount" integer NOT NULL DEFAULT '0', "referredByCode" character varying, "referralCode" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_b7f8278f4e89249bb75c9a15899" UNIQUE ("referralCode"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a000cca60bcf04454e72769949" ON "users"  ("phone") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users"  ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b7f8278f4e89249bb75c9a1589" ON "users"  ("referralCode") `);
        await queryRunner.query(`CREATE TYPE "public"."driver_profiles_level_enum" AS ENUM('rookie', 'standard', 'silver', 'gold', 'platinum', 'diamond', 'elite')`);
        await queryRunner.query(`CREATE TYPE "public"."driver_profiles_approvalstatus_enum" AS ENUM('pending', 'under_review', 'approved', 'rejected', 'suspended')`);
        await queryRunner.query(`CREATE TYPE "public"."driver_profiles_kycstatus_enum" AS ENUM('not_started', 'submitted', 'verified', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."driver_profiles_availability_enum" AS ENUM('offline', 'online', 'on_trip')`);
        await queryRunner.query(`CREATE TABLE "driver_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "level" "public"."driver_profiles_level_enum" NOT NULL DEFAULT 'rookie', "approvalStatus" "public"."driver_profiles_approvalstatus_enum" NOT NULL DEFAULT 'pending', "kycStatus" "public"."driver_profiles_kycstatus_enum" NOT NULL DEFAULT 'not_started', "availability" "public"."driver_profiles_availability_enum" NOT NULL DEFAULT 'offline', "city" character varying, "rating" numeric(3,2) NOT NULL DEFAULT '5', "ratingCount" integer NOT NULL DEFAULT '0', "totalTrips" integer NOT NULL DEFAULT '0', "completedTrips" integer NOT NULL DEFAULT '0', "cancelledTrips" integer NOT NULL DEFAULT '0', "commissionOverridePercent" numeric(5,2), "activeVehicleId" character varying, "fleetCompanyId" character varying, "licenseNumber" character varying, "licenseExpiry" TIMESTAMP, "currentLat" double precision, "currentLng" double precision, "locationUpdatedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_c22d0ffc4bff60e9a39c003759" UNIQUE ("userId"), CONSTRAINT "PK_6e002fc8a835351e070978fcad4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c22d0ffc4bff60e9a39c003759" ON "driver_profiles"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "incident_timeline_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "incidentId" character varying NOT NULL, "actorUserId" character varying, "action" character varying NOT NULL, "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_41e0f8cba5ce737be506c445d65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1bee66089e3c6108089f1b4f74" ON "incident_timeline_entries"  ("incidentId") `);
        await queryRunner.query(`CREATE TYPE "public"."incidents_type_enum" AS ENUM('sos', 'safety_concern', 'accident', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."incidents_status_enum" AS ENUM('open', 'acknowledged', 'resolved', 'closed')`);
        await queryRunner.query(`CREATE TABLE "incidents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."incidents_type_enum" NOT NULL, "reportedByUserId" character varying NOT NULL, "rideId" character varying, "status" "public"."incidents_status_enum" NOT NULL DEFAULT 'open', "description" text NOT NULL, "lat" double precision, "lng" double precision, "acknowledgedBy" character varying, "resolvedBy" character varying, "resolutionNotes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "resolvedAt" TIMESTAMP, CONSTRAINT "PK_ccb34c01719889017e2246469f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b166bfaba20d8509f33ccbc33" ON "incidents"  ("reportedByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_60d6737cacae7e1f6ec6a4dda6" ON "incidents"  ("rideId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6fa7e61c79777de95b6a4ecd63" ON "incidents"  ("status") `);
        await queryRunner.query(`CREATE TABLE "feature_flags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying, "isEnabled" boolean NOT NULL DEFAULT true, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_36d0344370584b4d6a953c53a69" UNIQUE ("key"), CONSTRAINT "PK_db657d344e9caacfc9d5cf8bbac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_36d0344370584b4d6a953c53a6" ON "feature_flags"  ("key") `);
        await queryRunner.query(`CREATE TABLE "fleet_companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ownerUserId" character varying NOT NULL, "name" character varying NOT NULL, "registrationNumber" character varying, "city" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b4f81ccfaab8de68f6c7181fd73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4ca909ea645664a2f10a4d33c" ON "fleet_companies"  ("ownerUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."fleet_payouts_status_enum" AS ENUM('pending', 'processing', 'success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "fleet_payouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fleetCompanyId" character varying NOT NULL, "amount" numeric(14,2) NOT NULL, "bankAccountNumber" character varying NOT NULL, "bankCode" character varying NOT NULL, "status" "public"."fleet_payouts_status_enum" NOT NULL DEFAULT 'pending', "simulated" boolean NOT NULL DEFAULT false, "paystackTransferCode" character varying, "failureReason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_56d4960c5aa0cf660a263b3d09a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c5acc48000755e3a1aca2af0f" ON "fleet_payouts"  ("fleetCompanyId") `);
        await queryRunner.query(`CREATE TYPE "public"."fleet_staff_role_enum" AS ENUM('owner', 'manager')`);
        await queryRunner.query(`CREATE TABLE "fleet_staff" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fleetCompanyId" character varying NOT NULL, "userId" character varying NOT NULL, "role" "public"."fleet_staff_role_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_14fa37274435e06bd3afda35437" UNIQUE ("userId"), CONSTRAINT "PK_e44af4d73974ed127e003f2fee6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_246ac9ab528b17af9f62a21e70" ON "fleet_staff"  ("fleetCompanyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_14fa37274435e06bd3afda3543" ON "fleet_staff"  ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."fleet_transactions_direction_enum" AS ENUM('credit', 'debit')`);
        await queryRunner.query(`CREATE TYPE "public"."fleet_transactions_category_enum" AS ENUM('ride_earning', 'payout', 'adjustment')`);
        await queryRunner.query(`CREATE TABLE "fleet_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fleetWalletId" character varying NOT NULL, "direction" "public"."fleet_transactions_direction_enum" NOT NULL, "category" "public"."fleet_transactions_category_enum" NOT NULL, "amount" numeric(14,2) NOT NULL, "balanceAfter" numeric(14,2) NOT NULL, "referenceId" character varying, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5f954152e36428a6c057fb1ab19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e6c08f3e76988b0cde19a79de0" ON "fleet_transactions"  ("fleetWalletId") `);
        await queryRunner.query(`CREATE TABLE "fleet_wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fleetCompanyId" character varying NOT NULL, "balance" numeric(14,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'NGN', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_00930bd9fe7a599d16c36b1ec09" UNIQUE ("fleetCompanyId"), CONSTRAINT "PK_6a0aadce9a96312a779280a20ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_00930bd9fe7a599d16c36b1ec0" ON "fleet_wallets"  ("fleetCompanyId") `);
        await queryRunner.query(`CREATE TYPE "public"."fraud_flags_type_enum" AS ENUM('duplicate_account', 'gps_spoof', 'referral_abuse', 'multiple_accounts_same_device')`);
        await queryRunner.query(`CREATE TYPE "public"."fraud_flags_severity_enum" AS ENUM('low', 'medium', 'high')`);
        await queryRunner.query(`CREATE TYPE "public"."fraud_flags_status_enum" AS ENUM('open', 'reviewed', 'dismissed')`);
        await queryRunner.query(`CREATE TABLE "fraud_flags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."fraud_flags_type_enum" NOT NULL, "userId" character varying NOT NULL, "relatedUserId" character varying, "severity" "public"."fraud_flags_severity_enum" NOT NULL DEFAULT 'medium', "details" jsonb, "status" "public"."fraud_flags_status_enum" NOT NULL DEFAULT 'open', "reviewedBy" character varying, "reviewNotes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_00fccadb758d1624e0831fe026a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35fd81a783ee7aad37fe14d7c2" ON "fraud_flags"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_64991cb2431fb6c479f1aedacd" ON "fraud_flags"  ("status") `);
        await queryRunner.query(`CREATE TABLE "user_devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "fingerprint" character varying NOT NULL, "ipAddress" character varying, "firstSeenAt" TIMESTAMP NOT NULL DEFAULT now(), "lastSeenAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c9e7e648903a9e537347aba4371" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e12ac4f8016243ac71fd2e415a" ON "user_devices"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_87704bb72ef70822c6a6e6a566" ON "user_devices"  ("fingerprint") `);
        await queryRunner.query(`CREATE TYPE "public"."driver_incentive_progress_status_enum" AS ENUM('in_progress', 'completed', 'rewarded')`);
        await queryRunner.query(`CREATE TABLE "driver_incentive_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "incentiveId" character varying NOT NULL, "driverId" character varying NOT NULL, "tripsCompleted" integer NOT NULL DEFAULT '0', "windowStartedAt" TIMESTAMP, "status" "public"."driver_incentive_progress_status_enum" NOT NULL DEFAULT 'in_progress', "completedAt" TIMESTAMP, "rewardedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_54e52397bbe2800c139109397c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_401c4d5d1e2b8a2ea83efbc348" ON "driver_incentive_progress"  ("incentiveId") `);
        await queryRunner.query(`CREATE INDEX "IDX_39e61d279fb5c74a07b927458d" ON "driver_incentive_progress"  ("driverId") `);
        await queryRunner.query(`CREATE TYPE "public"."incentives_type_enum" AS ENUM('streak', 'quest', 'peak_hour', 'milestone')`);
        await queryRunner.query(`CREATE TABLE "incentives" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "type" "public"."incentives_type_enum" NOT NULL, "targetTrips" integer, "windowHours" integer, "peakStartHour" integer, "peakEndHour" integer, "rewardAmount" numeric(10,2) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d32a03056b7ceaa502e2b814561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_orders_category_enum" AS ENUM('parcel', 'food', 'grocery', 'pharmacy', 'courier')`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_orders_status_enum" AS ENUM('requested', 'searching', 'accepted', 'pickup_arrived', 'picked_up', 'in_transit', 'delivered', 'cancelled', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_orders_paymentmethod_enum" AS ENUM('card', 'wallet', 'cash', 'bank_transfer', 'corporate')`);
        await queryRunner.query(`CREATE TYPE "public"."delivery_orders_cancelledby_enum" AS ENUM('customer', 'driver', 'system')`);
        await queryRunner.query(`CREATE TABLE "delivery_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customerId" character varying NOT NULL, "driverId" character varying, "vehicleId" character varying, "category" "public"."delivery_orders_category_enum" NOT NULL, "status" "public"."delivery_orders_status_enum" NOT NULL DEFAULT 'requested', "pickupLat" double precision NOT NULL, "pickupLng" double precision NOT NULL, "pickupAddress" character varying NOT NULL, "pickupContactName" character varying NOT NULL, "pickupContactPhone" character varying NOT NULL, "dropoffLat" double precision NOT NULL, "dropoffLng" double precision NOT NULL, "dropoffAddress" character varying NOT NULL, "dropoffContactName" character varying NOT NULL, "dropoffContactPhone" character varying NOT NULL, "itemDescription" character varying NOT NULL, "itemValue" numeric(10,2), "weightKg" numeric(6,2), "requiresSignature" boolean NOT NULL DEFAULT false, "isCod" boolean NOT NULL DEFAULT false, "codAmount" numeric(10,2), "city" character varying, "estimatedDistanceKm" double precision, "baseFare" numeric(10,2) NOT NULL, "distanceFare" numeric(10,2) NOT NULL, "weightFare" numeric(10,2) NOT NULL DEFAULT '0', "discount" numeric(10,2) NOT NULL DEFAULT '0', "totalFare" numeric(10,2) NOT NULL, "paymentMethod" "public"."delivery_orders_paymentmethod_enum" NOT NULL DEFAULT 'cash', "commissionPercent" numeric(5,2), "commissionAmount" numeric(10,2), "driverEarnings" numeric(10,2), "earningsSettled" boolean NOT NULL DEFAULT false, "cancelledBy" "public"."delivery_orders_cancelledby_enum", "cancelReason" character varying, "acceptedAt" TIMESTAMP, "pickedUpAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "cancelledAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_29e637736a0b5f36946edec3650" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb142a45206c02f3c0dceff300" ON "delivery_orders"  ("customerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b8e15adca01a0ff7438743e93" ON "delivery_orders"  ("driverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_33e8ad209aee13066c88edb083" ON "delivery_orders"  ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."device_tokens_platform_enum" AS ENUM('ios', 'android', 'web')`);
        await queryRunner.query(`CREATE TABLE "device_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "token" character varying NOT NULL, "platform" "public"."device_tokens_platform_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_977e24c520c49436d08e5eeea8a" UNIQUE ("token"), CONSTRAINT "PK_84700be257607cfb1f9dc2e52c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_511957e3e8443429dc3fb00120" ON "device_tokens"  ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_977e24c520c49436d08e5eeea8" ON "device_tokens"  ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('push', 'sms', 'email', 'whatsapp', 'in_app')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'sent', 'failed', 'simulated')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "channel" "public"."notifications_channel_enum" NOT NULL, "title" character varying NOT NULL, "body" text NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "isRead" boolean NOT NULL DEFAULT false, "metadata" jsonb, "failureReason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "emergency_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "name" character varying NOT NULL, "phone" character varying NOT NULL, "relationship" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8be191845b6fca1c4e5ba5bd7d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b9bb7f85035305c3dee924d22" ON "emergency_contacts"  ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."favourite_places_type_enum" AS ENUM('home', 'work', 'other')`);
        await queryRunner.query(`CREATE TABLE "favourite_places" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "type" "public"."favourite_places_type_enum" NOT NULL DEFAULT 'other', "label" character varying NOT NULL, "lat" double precision NOT NULL, "lng" double precision NOT NULL, "address" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4bdafe083bdd696b669ab587cff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d4e64ff199460ab70b3ff8784b" ON "favourite_places"  ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."passenger_profiles_chatpreference_enum" AS ENUM('chatty', 'quiet', 'no_preference')`);
        await queryRunner.query(`CREATE TYPE "public"."passenger_profiles_verificationstatus_enum" AS ENUM('not_started', 'submitted', 'verified', 'failed')`);
        await queryRunner.query(`CREATE TABLE "passenger_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "preferredLanguage" character varying, "musicPreference" character varying, "chatPreference" "public"."passenger_profiles_chatpreference_enum" NOT NULL DEFAULT 'no_preference', "wheelchairAccessible" boolean NOT NULL DEFAULT false, "verificationStatus" "public"."passenger_profiles_verificationstatus_enum" NOT NULL DEFAULT 'not_started', "idDocumentUrl" character varying, "isBlacklisted" boolean NOT NULL DEFAULT false, "blacklistReason" character varying, "totalRides" integer NOT NULL DEFAULT '0', "completedRides" integer NOT NULL DEFAULT '0', "cancelledRides" integer NOT NULL DEFAULT '0', "totalSpend" numeric(14,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_d5434dccdc9c9393c5deb85624" UNIQUE ("userId"), CONSTRAINT "PK_70936a0d464b476507cf4f2889e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d5434dccdc9c9393c5deb85624" ON "passenger_profiles"  ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_records_method_enum" AS ENUM('card', 'wallet', 'cash', 'bank_transfer', 'corporate')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_records_status_enum" AS ENUM('pending', 'success', 'failed', 'refunded', 'partially_refunded')`);
        await queryRunner.query(`CREATE TABLE "payment_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rideId" character varying, "userId" character varying NOT NULL, "method" "public"."payment_records_method_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "status" "public"."payment_records_status_enum" NOT NULL DEFAULT 'pending', "reference" character varying NOT NULL, "simulated" boolean NOT NULL DEFAULT false, "gatewayReference" character varying, "failureReason" character varying, "refundedAmount" numeric(10,2), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_942aced0e017d131d86c36dfd50" UNIQUE ("reference"), CONSTRAINT "PK_1770b3d8261895c6bafd8faef91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_246bcf53a7433a00a0cb0df045" ON "payment_records"  ("rideId") `);
        await queryRunner.query(`CREATE INDEX "IDX_41de67d533d144d2bda950975b" ON "payment_records"  ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_942aced0e017d131d86c36dfd5" ON "payment_records"  ("reference") `);
        await queryRunner.query(`CREATE TABLE "saved_cards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "authorizationCode" character varying NOT NULL, "last4" character varying, "cardType" character varying, "bank" character varying, "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f1fa1708e52bdeeb54eae1c5bd6" UNIQUE ("authorizationCode"), CONSTRAINT "PK_00718d0da00daa3aec1e7881cbc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e66cfc6746ba4ab45a9fb6458c" ON "saved_cards"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "startDate" TIMESTAMP, "endDate" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_831e3fcd4fc45b4e4c3f57a9ee4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "promotion_redemptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "promotionId" character varying NOT NULL, "userId" character varying NOT NULL, "rideId" character varying, "discountAmount" numeric(10,2) NOT NULL, "redeemedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17e98da71097f78ff330df148f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6fe6571338dcc58ad782a14a8" ON "promotion_redemptions"  ("promotionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5695a542b7477ef875553598e5" ON "promotion_redemptions"  ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."promotions_type_enum" AS ENUM('percentage', 'fixed_amount', 'cashback')`);
        await queryRunner.query(`CREATE TABLE "promotions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "description" character varying, "type" "public"."promotions_type_enum" NOT NULL, "value" numeric(10,2) NOT NULL, "maxDiscountAmount" numeric(10,2), "minFareAmount" numeric(10,2), "usageLimitTotal" integer, "usageLimitPerUser" integer NOT NULL DEFAULT '1', "timesRedeemed" integer NOT NULL DEFAULT '0', "validFrom" TIMESTAMP, "validUntil" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "campaignId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8ab10e580f70c3d2e2e4b31ebf2" UNIQUE ("code"), CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8ab10e580f70c3d2e2e4b31ebf" ON "promotions"  ("code") `);
        await queryRunner.query(`CREATE TABLE "referral_grants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referrerUserId" character varying NOT NULL, "refereeUserId" character varying NOT NULL, "referrerBonus" numeric(10,2) NOT NULL, "refereeBonus" numeric(10,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_585e27a52cb5f1b0508e4f0f54c" UNIQUE ("refereeUserId"), CONSTRAINT "PK_dd0f56baece87bab3944b5dc2fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a856e2cb570de90d0e46e97e00" ON "referral_grants"  ("referrerUserId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_585e27a52cb5f1b0508e4f0f54" ON "referral_grants"  ("refereeUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."cash_reconciliations_status_enum" AS ENUM('pending', 'settled', 'written_off')`);
        await queryRunner.query(`CREATE TABLE "cash_reconciliations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverId" character varying, "fleetCompanyId" character varying, "rideId" character varying NOT NULL, "amountOwed" numeric(10,2) NOT NULL, "status" "public"."cash_reconciliations_status_enum" NOT NULL DEFAULT 'pending', "writtenOffBy" character varying, "writeOffReason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "settledAt" TIMESTAMP, CONSTRAINT "PK_367e7995e9b1f6a1d889a5ddb3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a142eef4e50f54423463003ad7" ON "cash_reconciliations"  ("driverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3107162f50654fd45158ddf22" ON "cash_reconciliations"  ("fleetCompanyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6f18aacf6aeb9106b65bcf30a" ON "cash_reconciliations"  ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."rides_category_enum" AS ENUM('economy', 'comfort', 'executive', 'xl', 'suv', 'electric', 'motorcycle', 'tricycle', 'taxi', 'luxury')`);
        await queryRunner.query(`CREATE TYPE "public"."rides_status_enum" AS ENUM('scheduled', 'requested', 'searching', 'accepted', 'arriving', 'arrived', 'in_progress', 'completed', 'cancelled', 'no_driver_found')`);
        await queryRunner.query(`CREATE TYPE "public"."rides_paymentmethod_enum" AS ENUM('card', 'wallet', 'cash', 'bank_transfer', 'corporate')`);
        await queryRunner.query(`CREATE TYPE "public"."rides_cancelledby_enum" AS ENUM('passenger', 'driver', 'system')`);
        await queryRunner.query(`CREATE TABLE "rides" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "passengerId" character varying NOT NULL, "driverId" character varying, "vehicleId" character varying, "category" "public"."rides_category_enum" NOT NULL, "status" "public"."rides_status_enum" NOT NULL DEFAULT 'requested', "pickupLat" double precision NOT NULL, "pickupLng" double precision NOT NULL, "pickupAddress" character varying NOT NULL, "dropoffLat" double precision NOT NULL, "dropoffLng" double precision NOT NULL, "dropoffAddress" character varying NOT NULL, "stops" jsonb, "city" character varying, "estimatedDistanceKm" double precision, "estimatedDurationMin" integer, "baseFare" numeric(10,2) NOT NULL, "distanceFare" numeric(10,2) NOT NULL, "timeFare" numeric(10,2) NOT NULL, "surgeMultiplier" numeric(4,2) NOT NULL DEFAULT '1', "nightMultiplierApplied" numeric(4,2) NOT NULL DEFAULT '1', "airportFee" numeric(10,2) NOT NULL DEFAULT '0', "waitingFee" numeric(10,2) NOT NULL DEFAULT '0', "cancellationFee" numeric(10,2), "tollFare" numeric(10,2) NOT NULL DEFAULT '0', "discount" numeric(10,2) NOT NULL DEFAULT '0', "totalFare" numeric(10,2) NOT NULL, "usedRealRouting" boolean NOT NULL DEFAULT false, "isAirportTrip" boolean NOT NULL DEFAULT false, "flightNumber" character varying, "scheduledAt" TIMESTAMP, "commissionPercent" numeric(5,2), "commissionAmount" numeric(10,2), "driverEarnings" numeric(10,2), "earningsSettled" boolean NOT NULL DEFAULT false, "paymentMethod" "public"."rides_paymentmethod_enum" NOT NULL DEFAULT 'cash', "passengerRating" integer, "passengerRatingComment" character varying, "driverRating" integer, "driverRatingComment" character varying, "cancelledBy" "public"."rides_cancelledby_enum", "cancelReason" character varying, "acceptedAt" TIMESTAMP, "arrivedAt" TIMESTAMP, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "cancelledAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca6f62fc1e999b139c7f28f07fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bf2d633c1f19708b7998b9e6d" ON "rides"  ("passengerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0adda088d567495e71d21b6c69" ON "rides"  ("driverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b9253c85be51e3785d3653a8" ON "rides"  ("status") `);
        await queryRunner.query(`CREATE TABLE "system_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "value" text NOT NULL, "description" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b1b5bc664526d375c94ce9ad43d" UNIQUE ("key"), CONSTRAINT "PK_82521f08790d248b2a80cc85d40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b1b5bc664526d375c94ce9ad43" ON "system_settings"  ("key") `);
        await queryRunner.query(`CREATE TYPE "public"."support_tickets_category_enum" AS ENUM('general', 'ride_issue', 'payment_issue', 'account_issue', 'lost_item', 'safety')`);
        await queryRunner.query(`CREATE TYPE "public"."support_tickets_status_enum" AS ENUM('open', 'in_progress', 'resolved', 'closed')`);
        await queryRunner.query(`CREATE TYPE "public"."support_tickets_priority_enum" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "support_tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "category" "public"."support_tickets_category_enum" NOT NULL DEFAULT 'general', "subject" character varying NOT NULL, "description" text NOT NULL, "status" "public"."support_tickets_status_enum" NOT NULL DEFAULT 'open', "priority" "public"."support_tickets_priority_enum" NOT NULL DEFAULT 'normal', "rideId" character varying, "assignedAgentId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "resolvedAt" TIMESTAMP, CONSTRAINT "PK_942e8d8f5df86100471d2324643" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8679e2ff150ff0e253189ca025" ON "support_tickets"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba7b1a2ed4051fb3b39ff95444" ON "support_tickets"  ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f446e726dada8732c6534fbc0" ON "support_tickets"  ("rideId") `);
        await queryRunner.query(`CREATE TABLE "ticket_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticketId" character varying NOT NULL, "senderId" character varying NOT NULL, "senderRole" character varying NOT NULL, "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_37beb692dedf7eccb4e519ccec1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b01e2a35417efbe04c10828266" ON "ticket_messages"  ("ticketId") `);
        await queryRunner.query(`CREATE TABLE "location_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverUserId" character varying NOT NULL, "rideId" character varying, "lat" double precision NOT NULL, "lng" double precision NOT NULL, "recordedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_969935adbd171d824b649bc03d8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4668c1a8f998688d473325d080" ON "location_history"  ("driverUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5843232efd66eb9782352cfe4" ON "location_history"  ("rideId") `);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_category_enum" AS ENUM('car', 'suv', 'taxi', 'luxury', 'ev', 'motorcycle', 'tricycle', 'van', 'bus', 'truck')`);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_status_enum" AS ENUM('pending_inspection', 'active', 'maintenance', 'deactivated')`);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "driverId" character varying NOT NULL, "fleetCompanyId" character varying, "category" "public"."vehicles_category_enum" NOT NULL, "make" character varying NOT NULL, "model" character varying NOT NULL, "year" integer NOT NULL, "color" character varying, "plateNumber" character varying NOT NULL, "vin" character varying, "insuranceExpiry" TIMESTAMP, "roadWorthinessExpiry" TIMESTAMP, "photoUrl" character varying, "status" "public"."vehicles_status_enum" NOT NULL DEFAULT 'pending_inspection', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_66ea96381a7a7ceb35c72f36625" UNIQUE ("plateNumber"), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_28d7607488252336b22511e9e8" ON "vehicles"  ("driverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_677bc1977dc21a263b20dc5cc1" ON "vehicles"  ("fleetCompanyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_66ea96381a7a7ceb35c72f3662" ON "vehicles"  ("plateNumber") `);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "balance" numeric(14,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'NGN', "isFrozen" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_2ecdb33f23e9a6fc392025c0b9" UNIQUE ("userId"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2ecdb33f23e9a6fc392025c0b9" ON "wallets"  ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_direction_enum" AS ENUM('credit', 'debit')`);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_category_enum" AS ENUM('ride_payment', 'ride_earning', 'commission', 'topup', 'withdrawal', 'refund', 'bonus', 'cashback', 'referral', 'cancellation_fee', 'delivery_payment', 'delivery_earning')`);
        await queryRunner.query(`CREATE TABLE "wallet_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletId" uuid NOT NULL, "direction" "public"."wallet_transactions_direction_enum" NOT NULL, "category" "public"."wallet_transactions_category_enum" NOT NULL, "amount" numeric(14,2) NOT NULL, "balanceAfter" numeric(14,2) NOT NULL, "referenceId" character varying, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5120f131bde2cda940ec1a621db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8a94d9d61a2b05123710b325fb" ON "wallet_transactions"  ("walletId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5cda9aeb8e1321378789f85c79" ON "wallet_transactions"  ("referenceId") `);
        await queryRunner.query(`CREATE TYPE "public"."webhook_delivery_logs_status_enum" AS ENUM('success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "webhook_delivery_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscriptionId" character varying NOT NULL, "event" character varying NOT NULL, "payload" jsonb NOT NULL, "status" "public"."webhook_delivery_logs_status_enum" NOT NULL, "responseCode" integer, "errorMessage" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0e3b1d3f1b9b79d4a7ad0b92b84" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5211de203520b0ec8cd59d8448" ON "webhook_delivery_logs"  ("subscriptionId") `);
        await queryRunner.query(`CREATE TABLE "webhook_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "partnerName" character varying NOT NULL, "url" character varying NOT NULL, "secret" character varying NOT NULL, "events" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bf631ae77d39849d599817fb6f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "driver_profiles" ADD CONSTRAINT "FK_c22d0ffc4bff60e9a39c0037590" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passenger_profiles" ADD CONSTRAINT "FK_d5434dccdc9c9393c5deb856244" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_8a94d9d61a2b05123710b325fbf" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_8a94d9d61a2b05123710b325fbf"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`ALTER TABLE "passenger_profiles" DROP CONSTRAINT "FK_d5434dccdc9c9393c5deb856244"`);
        await queryRunner.query(`ALTER TABLE "driver_profiles" DROP CONSTRAINT "FK_c22d0ffc4bff60e9a39c0037590"`);
        await queryRunner.query(`DROP TABLE "webhook_subscriptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5211de203520b0ec8cd59d8448"`);
        await queryRunner.query(`DROP TABLE "webhook_delivery_logs"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_delivery_logs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5cda9aeb8e1321378789f85c79"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a94d9d61a2b05123710b325fb"`);
        await queryRunner.query(`DROP TABLE "wallet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ecdb33f23e9a6fc392025c0b9"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66ea96381a7a7ceb35c72f3662"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_677bc1977dc21a263b20dc5cc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28d7607488252336b22511e9e8"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5843232efd66eb9782352cfe4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4668c1a8f998688d473325d080"`);
        await queryRunner.query(`DROP TABLE "location_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b01e2a35417efbe04c10828266"`);
        await queryRunner.query(`DROP TABLE "ticket_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f446e726dada8732c6534fbc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba7b1a2ed4051fb3b39ff95444"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8679e2ff150ff0e253189ca025"`);
        await queryRunner.query(`DROP TABLE "support_tickets"`);
        await queryRunner.query(`DROP TYPE "public"."support_tickets_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."support_tickets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."support_tickets_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1b5bc664526d375c94ce9ad43"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b9253c85be51e3785d3653a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0adda088d567495e71d21b6c69"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bf2d633c1f19708b7998b9e6d"`);
        await queryRunner.query(`DROP TABLE "rides"`);
        await queryRunner.query(`DROP TYPE "public"."rides_cancelledby_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rides_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rides_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rides_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6f18aacf6aeb9106b65bcf30a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3107162f50654fd45158ddf22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a142eef4e50f54423463003ad7"`);
        await queryRunner.query(`DROP TABLE "cash_reconciliations"`);
        await queryRunner.query(`DROP TYPE "public"."cash_reconciliations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_585e27a52cb5f1b0508e4f0f54"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a856e2cb570de90d0e46e97e00"`);
        await queryRunner.query(`DROP TABLE "referral_grants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ab10e580f70c3d2e2e4b31ebf"`);
        await queryRunner.query(`DROP TABLE "promotions"`);
        await queryRunner.query(`DROP TYPE "public"."promotions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5695a542b7477ef875553598e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6fe6571338dcc58ad782a14a8"`);
        await queryRunner.query(`DROP TABLE "promotion_redemptions"`);
        await queryRunner.query(`DROP TABLE "campaigns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e66cfc6746ba4ab45a9fb6458c"`);
        await queryRunner.query(`DROP TABLE "saved_cards"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_942aced0e017d131d86c36dfd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41de67d533d144d2bda950975b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_246bcf53a7433a00a0cb0df045"`);
        await queryRunner.query(`DROP TABLE "payment_records"`);
        await queryRunner.query(`DROP TYPE "public"."payment_records_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_records_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5434dccdc9c9393c5deb85624"`);
        await queryRunner.query(`DROP TABLE "passenger_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."passenger_profiles_verificationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."passenger_profiles_chatpreference_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4e64ff199460ab70b3ff8784b"`);
        await queryRunner.query(`DROP TABLE "favourite_places"`);
        await queryRunner.query(`DROP TYPE "public"."favourite_places_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b9bb7f85035305c3dee924d22"`);
        await queryRunner.query(`DROP TABLE "emergency_contacts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_977e24c520c49436d08e5eeea8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_511957e3e8443429dc3fb00120"`);
        await queryRunner.query(`DROP TABLE "device_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."device_tokens_platform_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33e8ad209aee13066c88edb083"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b8e15adca01a0ff7438743e93"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb142a45206c02f3c0dceff300"`);
        await queryRunner.query(`DROP TABLE "delivery_orders"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_orders_cancelledby_enum"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_orders_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."delivery_orders_category_enum"`);
        await queryRunner.query(`DROP TABLE "incentives"`);
        await queryRunner.query(`DROP TYPE "public"."incentives_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39e61d279fb5c74a07b927458d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_401c4d5d1e2b8a2ea83efbc348"`);
        await queryRunner.query(`DROP TABLE "driver_incentive_progress"`);
        await queryRunner.query(`DROP TYPE "public"."driver_incentive_progress_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87704bb72ef70822c6a6e6a566"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12ac4f8016243ac71fd2e415a"`);
        await queryRunner.query(`DROP TABLE "user_devices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64991cb2431fb6c479f1aedacd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35fd81a783ee7aad37fe14d7c2"`);
        await queryRunner.query(`DROP TABLE "fraud_flags"`);
        await queryRunner.query(`DROP TYPE "public"."fraud_flags_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fraud_flags_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fraud_flags_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00930bd9fe7a599d16c36b1ec0"`);
        await queryRunner.query(`DROP TABLE "fleet_wallets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6c08f3e76988b0cde19a79de0"`);
        await queryRunner.query(`DROP TABLE "fleet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."fleet_transactions_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fleet_transactions_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14fa37274435e06bd3afda3543"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_246ac9ab528b17af9f62a21e70"`);
        await queryRunner.query(`DROP TABLE "fleet_staff"`);
        await queryRunner.query(`DROP TYPE "public"."fleet_staff_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c5acc48000755e3a1aca2af0f"`);
        await queryRunner.query(`DROP TABLE "fleet_payouts"`);
        await queryRunner.query(`DROP TYPE "public"."fleet_payouts_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4ca909ea645664a2f10a4d33c"`);
        await queryRunner.query(`DROP TABLE "fleet_companies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36d0344370584b4d6a953c53a6"`);
        await queryRunner.query(`DROP TABLE "feature_flags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fa7e61c79777de95b6a4ecd63"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60d6737cacae7e1f6ec6a4dda6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b166bfaba20d8509f33ccbc33"`);
        await queryRunner.query(`DROP TABLE "incidents"`);
        await queryRunner.query(`DROP TYPE "public"."incidents_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."incidents_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bee66089e3c6108089f1b4f74"`);
        await queryRunner.query(`DROP TABLE "incident_timeline_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c22d0ffc4bff60e9a39c003759"`);
        await queryRunner.query(`DROP TABLE "driver_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."driver_profiles_availability_enum"`);
        await queryRunner.query(`DROP TYPE "public"."driver_profiles_kycstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."driver_profiles_approvalstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."driver_profiles_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7f8278f4e89249bb75c9a1589"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2841db94a1991f825d16e9dfb"`);
        await queryRunner.query(`DROP TABLE "driver_documents"`);
        await queryRunner.query(`DROP TYPE "public"."driver_documents_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."driver_documents_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2883d65c5168c5708990302325"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e47debd3d44368f977ae7b6b81"`);
        await queryRunner.query(`DROP TABLE "ride_offers"`);
        await queryRunner.query(`DROP TYPE "public"."ride_offers_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be01460a12c312aa6bca798de6"`);
        await queryRunner.query(`DROP TABLE "corporate_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."corporate_transactions_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab843c3599b19d51dc6d7cca47"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55c425dde4e4d3b2c5fd4a1ecc"`);
        await queryRunner.query(`DROP TABLE "corporate_employees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_541734cca61b7cb40ab27085e3"`);
        await queryRunner.query(`DROP TABLE "corporate_accounts"`);
        await queryRunner.query(`DROP TABLE "commission_rules"`);
        await queryRunner.query(`DROP TYPE "public"."commission_rules_vehiclecategory_enum"`);
        await queryRunner.query(`DROP TYPE "public"."commission_rules_driverlevel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_164bf011d905e86e677bc86a1e"`);
        await queryRunner.query(`DROP TABLE "cms_pages"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d38771dd102800f389f4c73ae"`);
        await queryRunner.query(`DROP TABLE "otp_codes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fcfb9137823075fb3162b82f73"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e36d23e1e7cf81ea77758bef79"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d632a6c3b16bc708bf0987fed"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66b7b2c37c035081115fdde45b"`);
        await queryRunner.query(`DROP TABLE "airports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d2215326ea228a5b859b627a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b28c236bb7cfa154d8edc5f1f"`);
        await queryRunner.query(`DROP TABLE "airport_queue_entries"`);
        await queryRunner.query(`DROP TYPE "public"."airport_queue_entries_status_enum"`);
        await queryRunner.query(`DROP TABLE "sponsored_locations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fcffbe533565f62ddcbd966221"`);
        await queryRunner.query(`DROP TABLE "banner_ads"`);
        await queryRunner.query(`DROP TYPE "public"."banner_ads_placement_enum"`);
        await queryRunner.query(`DROP TABLE "ad_campaigns"`);
        await queryRunner.query(`DROP TYPE "public"."ad_campaigns_status_enum"`);
    }

}
